#!/usr/bin/env bash
# opencode-harness setup: wire a project to the OpenCode "zen" endpoint with
# capability profiles (fast / reasoning-heavy / code-generation).
# Idempotent. Safe to re-run. Pass --force to overwrite an existing config.
#
# Provenance (dogfood): first draft generated by glm-5.2 via the harness itself,
# reviewed + validated end-to-end by Claude. See references/model-routing.md.
set -euo pipefail

CONFIG_DIR="$HOME/.config/vinay-agent"
CONFIG_FILE="$CONFIG_DIR/config.toml"
ENDPOINT="https://opencode.ai/zen/v1/chat/completions"

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

# Step 1: API key
echo "Step 1: Checking OPENCODE_API_KEY..."
if [[ -z "${OPENCODE_API_KEY:-}" ]]; then
  echo "  OPENCODE_API_KEY is unset."
  echo "  Set it (e.g. in ~/.config/opencode/keys.env, then 'source' it):"
  echo "    export OPENCODE_API_KEY=<your-key>"
  echo "  Get a key at https://opencode.ai"
  exit 1
fi
echo "  ok"

# Step 2: opencode CLI
echo "Step 2: Checking for opencode CLI..."
if ! command -v opencode >/dev/null 2>&1; then
  echo "  opencode is not installed. Install with:"
  echo "    curl -fsSL https://opencode.ai/install | bash"
  exit 1
fi
echo "  ok ($(command -v opencode))"

# Step 3: config (never clobber without --force)
echo "Step 3: Ensuring config at $CONFIG_FILE..."
mkdir -p "$CONFIG_DIR"
if [[ -f "$CONFIG_FILE" && "$FORCE" -eq 0 ]]; then
  echo "  exists; leaving it (pass --force to overwrite)"
else
  cat > "$CONFIG_FILE" <<'EOF'
# OpenCode zen integration. Profiles map a capability to a model.
[llm]
provider = "openai-compatible"
endpoint = "https://opencode.ai/zen/v1/chat/completions"
model = "kimi-k2.6"
api_key_env = "OPENCODE_API_KEY"
max_tokens = 2048

[small_llm]
provider = "openai-compatible"
endpoint = "https://opencode.ai/zen/v1/chat/completions"
model = "kimi-k2.6"
api_key_env = "OPENCODE_API_KEY"
max_tokens = 512

[profiles.fast]
model = "kimi-k2.6"

[profiles.reasoning-heavy]
model = "glm-5.2"

[profiles.code-generation]
model = "glm-5.2"

[security]
triage_llm = "fast"
EOF
  echo "  wrote $CONFIG_FILE"
fi

# Step 4: end-to-end test — both models must answer
echo "Step 4: End-to-end model test..."
fail=0
for model in kimi-k2.6 glm-5.2; do
  body="{\"model\":\"$model\",\"messages\":[{\"role\":\"user\",\"content\":\"ping\"}],\"max_tokens\":8}"
  status=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$ENDPOINT" \
    -H "Authorization: Bearer $OPENCODE_API_KEY" \
    -H "Content-Type: application/json" -d "$body" 2>/dev/null) || status="000"
  if [[ "$status" == "200" ]]; then
    echo "  OK   $model"
  else
    echo "  FAIL $model (http $status)"  # 000 = offline/unreachable; 401 = bad key; 404 = unknown model
    fail=1
  fi
done

echo
if [[ "$fail" -eq 0 ]]; then
  echo "Harness ready. Profiles: fast=kimi-k2.6  reasoning-heavy=glm-5.2  code-generation=glm-5.2"
else
  echo "Setup wrote config but a model test FAILED — see the http code above. Harness not verified."
  exit 1
fi
